printWidth: 120
semi: false 
singleQuote: false 
jsxSingleQuote: false
trailingComma: "all"
useTabs: false
tabWidth: 2
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
endOfLine: "auto"
quoteProps: "as-needed"